name: golang-playground
description: A Helm charts for Kubernetes application
version: 0.0.1
home: https://k8s.community/
sources:
  - https://github.com/kuskmen/golang-playground
maintainers:
  - name: Kubernetes Community Authors
    email: k8s.community@gmail.com
engine: gotpl